version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.production
    container_name: erp-new-backend-production
    image: erp-new-backend-production:1.0.0
    ports:
      - "5121:80"
    volumes:
      - /opt/erp/Uploads:/app/Uploads
