export enum AUTH {
  BASE = "auth",
  LOGIN = AUTH.BASE + "/login",
  ME = AUTH.BASE + "/me",
  REGISTER = AUTH.BASE + "/register",
  MODIFYUSERDATA = AUTH.BASE + "/user",
  MODIFYPASSWORD = AUTH.BASE + "/password",
}

enum CUENTAS {
  BASE = "contableCuenta",
  GET = CUENTAS.BASE,
  GETALL = CUENTAS.BASE + "/all",
  GETMAYOR = CUENTAS.BASE + "/mayor",
  FIND = CUENTAS.BASE + "/",
  POST = CUENTAS.BASE,
  PUT = CUENTAS.BASE + "/",
  DELETE = CUENTAS.BASE + "/",
  ACCOUNT = CUENTAS.BASE + "/accountingReport",
  REPORTBALANCEGENERAL = CUENTAS.BASE + "/balanceGeneralReport",
  GETCUENTASACTIVOS = CUENTAS.BASE + "/getCuentasActivos",
}

enum ASIENTOS {
  BASE = "contableAsiento",
  GET = ASIENTOS.BASE,
  GETALL = ASIENTOS.BASE + "/all",
  FIND = ASIENTOS.BASE + "/",
  POST = ASIENTOS.BASE,
  PUT = ASIENTOS.BASE + "/",
  DELETE = ASIENTOS.BASE + "/",
  SAVELOCAL = ASIENTOS.BASE + "/saveLocal",
}

enum TIPOCOMPROBANTES {
  BASE = "contableTipoComprobante",
  GET = TIPOCOMPROBANTES.BASE,
  GETALL = TIPOCOMPROBANTES.BASE + "/all",
  FIND = TIPOCOMPROBANTES.BASE + "/",
  POST = TIPOCOMPROBANTES.BASE,
  PUT = TIPOCOMPROBANTES.BASE + "/",
  DELETE = TIPOCOMPROBANTES.BASE + "/",
}

enum DETALLEASIENTOS {
  BASE = "contableDetalleAsiento",
  GET = DETALLEASIENTOS.BASE,
  GETALL = DETALLEASIENTOS.BASE + "/all",
  GETBYASIENTO = DETALLEASIENTOS.BASE + "/getByAsiento/",
  GETBYCUENTA = DETALLEASIENTOS.BASE + "/getByCuenta/",
  FIND = DETALLEASIENTOS.BASE + "/",
  POST = DETALLEASIENTOS.BASE,
  PUT = DETALLEASIENTOS.BASE + "/",
  DELETE = DETALLEASIENTOS.BASE + "/",
  SUMASYSALDOS = DETALLEASIENTOS.BASE + "/accountingReport",
  REPORTFLUJOEFECTIVO = DETALLEASIENTOS.BASE + "/flujoEfectivoReport",
}

enum CATEGORIAS {
  BASE = "productoCategoria",
  GET = CATEGORIAS.BASE,
  GETALL = CATEGORIAS.BASE + "/all",
  FIND = CATEGORIAS.BASE + "/",
  POST = CATEGORIAS.BASE,
  PUT = CATEGORIAS.BASE + "/",
  DELETE = CATEGORIAS.BASE + "/",
}

enum CATEGORIACONTACTO {
  BASE = "recContactoCategoria",
  GET = CATEGORIACONTACTO.BASE,
  GETALL = CATEGORIACONTACTO.BASE + "/all",
  FIND = CATEGORIACONTACTO.BASE + "/",
  POST = CATEGORIACONTACTO.BASE,
  PUT = CATEGORIACONTACTO.BASE + "/",
  DELETE = CATEGORIACONTACTO.BASE + "/",
}

enum CONTACTO {
  BASE = "recContacto",
  GET = CONTACTO.BASE,
  GETALL = CONTACTO.BASE + "/all",
  FIND = CONTACTO.BASE + "/",
  POST = CONTACTO.BASE,
  PUT = CONTACTO.BASE + "/",
  DELETE = CONTACTO.BASE + "/",
  PADRE = CONTACTO.BASE + "/contactos/",
  ITCOMPANY = CONTACTO.BASE + "/esEmpresa",
}

enum MODULOCATEGORIA {
  BASE = "riCategoriaModulo",
  GET = MODULOCATEGORIA.BASE,
  GETALL = MODULOCATEGORIA.BASE + "/all",
  FIND = MODULOCATEGORIA.BASE + "/",
  POST = MODULOCATEGORIA.BASE,
  PUT = MODULOCATEGORIA.BASE + "/",
  DELETE = MODULOCATEGORIA.BASE + "/",
}

enum GRUPO {
  BASE = "recGrupo",
  GET = GRUPO.BASE,
  GETALL = GRUPO.BASE + "/all",
  FIND = GRUPO.BASE + "/",
  POST = GRUPO.BASE,
  PUT = GRUPO.BASE + "/",
  DELETE = GRUPO.BASE + "/",
  ACCESOS = GRUPO.BASE + "/accesos/",
}

enum MENU {
  BASE = "riMenu",
  GET = MENU.BASE,
  GETALL = MENU.BASE + "/all",
  FIND = MENU.BASE + "/",
  POST = MENU.BASE,
  PUT = MENU.BASE + "/",
  DELETE = MENU.BASE + "/",
  DASHBOARD = MENU.BASE + "/dashboard",
}

enum MODELO {
  BASE = "riModelo",
  GET = MODELO.BASE,
  GETALL = MODELO.BASE + "/all",
  FIND = MODELO.BASE + "/",
  POST = MODELO.BASE,
  PUT = MODELO.BASE + "/",
  DELETE = MODELO.BASE + "/",
}

enum PRODUCTO {
  BASE = "producto",
  GET = PRODUCTO.BASE,
  GETALL = PRODUCTO.BASE + "/all",
  FIND = PRODUCTO.BASE + "/",
  PUT = PRODUCTO.BASE + "/",
}

enum PRODUCTOBASE {
  BASE = "productoBase",
  GET = PRODUCTOBASE.BASE,
  GETALL = PRODUCTOBASE.BASE + "/all",
  FIND = PRODUCTOBASE.BASE + "/",
  POST = PRODUCTOBASE.BASE,
  PUT = PRODUCTOBASE.BASE + "/",
  DELETE = PRODUCTOBASE.BASE + "/",
  PUTATRIBUTOS = PRODUCTOBASE.BASE + "/atributos/",
}

enum PRODUCTOCATEGORIA {
  BASE = "productoCategoria",
  GET = PRODUCTOCATEGORIA.BASE,
  GETALL = PRODUCTOCATEGORIA.BASE + "/all",
  FIND = PRODUCTOCATEGORIA.BASE + "/",
  POST = PRODUCTOCATEGORIA.BASE,
  PUT = PRODUCTOCATEGORIA.BASE + "/",
  DELETE = PRODUCTOCATEGORIA.BASE + "/",
}

enum USUARIO {
  BASE = "recUsuario",
  GET = USUARIO.BASE,
  GETALL = USUARIO.BASE + "/all",
  FIND = USUARIO.BASE + "/",
  POST = USUARIO.BASE,
  PUT = USUARIO.BASE + "/",
  GRUPOS = USUARIO.BASE + "/grupos/",
  DELETE = USUARIO.BASE + "/",
}

enum BANCOS {
  BASE = "contableBanco",
  GET = BANCOS.BASE,
  GETALL = BANCOS.BASE + "/all",
  FIND = BANCOS.BASE + "/",
  POST = BANCOS.BASE,
  PUT = BANCOS.BASE + "/",
  DELETE = BANCOS.BASE + "/",
  GETBYCUENTA = BANCOS.BASE + "/getByCuenta/",
}

enum TIPOCAMBIO {
  BASE = "contableTipoCambio",
  GET = TIPOCAMBIO.BASE,
  GETALL = TIPOCAMBIO.BASE + "/all",
  FIND = TIPOCAMBIO.BASE + "/",
  POST = TIPOCAMBIO.BASE,
  PUT = TIPOCAMBIO.BASE + "/",
  DELETE = TIPOCAMBIO.BASE + "/",
  TODAY = TIPOCAMBIO.BASE + "/today",
}

enum ATRIBUTO {
  BASE = "productoAtributo",
  GET = ATRIBUTO.BASE,
  GETALL = ATRIBUTO.BASE + "/all",
  FIND = ATRIBUTO.BASE + "/",
  POST = ATRIBUTO.BASE,
  PUT = ATRIBUTO.BASE + "/",
  DELETE = ATRIBUTO.BASE + "/",
}

enum ATRIBUTOVALOR {
  BASE = "productoAtributoValor",
  GET = ATRIBUTOVALOR.BASE,
  GETBYATRIBUTO = ATRIBUTOVALOR.BASE + "/getByAtributo/",
  GETALL = ATRIBUTOVALOR.BASE + "/all",
  FIND = ATRIBUTOVALOR.BASE + "/",
  POST = ATRIBUTOVALOR.BASE,
  PUT = ATRIBUTOVALOR.BASE + "/",
  DELETE = ATRIBUTOVALOR.BASE + "/",
}
enum COMPRAORDEN {
  BASE = "compraOrden",
  GET = COMPRAORDEN.BASE,
  GETALL = COMPRAORDEN.BASE + "/all",
  FIND = COMPRAORDEN.BASE + "/",
  POST = COMPRAORDEN.BASE,
  PUT = COMPRAORDEN.BASE + "/",
  DELETE = COMPRAORDEN.BASE + "/",
}
enum VENTAORDEN {
  BASE = "ventaOrden",
  GET = VENTAORDEN.BASE,
  GETALL = VENTAORDEN.BASE + "/all",
  FIND = VENTAORDEN.BASE + "/",
  POST = VENTAORDEN.BASE,
  PUT = VENTAORDEN.BASE + "/",
  DELETE = VENTAORDEN.BASE + "/",
  TODAY = VENTAORDEN.BASE + "/today",
}
enum EMPRESA {
  BASE = "recEmpresa",
  GET = EMPRESA.BASE,
  GETALL = EMPRESA.BASE + "/all",
  FIND = EMPRESA.BASE + "/",
  POST = EMPRESA.BASE,
  PUT = EMPRESA.BASE + "/",
  DELETE = EMPRESA.BASE + "/",
}
enum LIBRODIARIO {
  BASE = "contableLibroDiario",
  GET = LIBRODIARIO.BASE,
  GETALL = LIBRODIARIO.BASE + "/all",
  ACTIVE = LIBRODIARIO.BASE + "/active",
  ACTIVEBOOK = LIBRODIARIO.BASE + "/desactive/",
  FIND = LIBRODIARIO.BASE + "/",
  POST = LIBRODIARIO.BASE,
  PUT = LIBRODIARIO.BASE + "/",
  DELETE = LIBRODIARIO.BASE + "/",
  CHANGE = LIBRODIARIO.BASE + "/cambiarLibro/",
  NEWIMPORTANT = LIBRODIARIO.BASE + "/nuevoImportante",
}
enum COMPARTIRLIBRODIARIO {
  BASE = "contableCompartirLibro",
  GET = COMPARTIRLIBRODIARIO.BASE,
  SHAREPRIVATE = COMPARTIRLIBRODIARIO.BASE,
  GETUSERSBYBOOK = COMPARTIRLIBRODIARIO.BASE + "/getUsersByBook/",
}

enum MONEDA {
  BASE = "moneda",
  GET = MONEDA.BASE,
  GETALL = MONEDA.BASE + "/all",
  FIND = MONEDA.BASE + "/",
  POST = MONEDA.BASE,
  PUT = MONEDA.BASE + "/",
  DELETE = MONEDA.BASE + "/",
}
enum CONTACTOBANCO {
  BASE = "RecContactoBanco",
  GET = CONTACTOBANCO.BASE,
  GETALL = CONTACTOBANCO.BASE + "/all",
  FIND = CONTACTOBANCO.BASE + "/",
  POST = CONTACTOBANCO.BASE,
  PUT = CONTACTOBANCO.BASE + "/",
  DELETE = CONTACTOBANCO.BASE + "/",
}
enum BANCO {
  BASE = "recBanco",
  GET = BANCO.BASE,
  GETALL = BANCO.BASE + "/all",
  FIND = BANCO.BASE + "/",
  POST = BANCO.BASE,
  PUT = BANCO.BASE + "/",
  DELETE = BANCO.BASE + "/",
}
enum METODOPAGO {
  BASE = "metodoPago",
  GET = METODOPAGO.BASE,
  GETALL = METODOPAGO.BASE + "/all",
  FIND = METODOPAGO.BASE + "/",
  POST = METODOPAGO.BASE,
  PUT = METODOPAGO.BASE + "/",
  DELETE = METODOPAGO.BASE + "/",
}

enum EFECTIVO {
  BASE = "efectivo",
  GETBYMONEDA = EFECTIVO.BASE + "/getByMoneda/",
  GET = EFECTIVO.BASE,
  GETALL = EFECTIVO.BASE + "/all",
  FIND = EFECTIVO.BASE + "/",
  POST = EFECTIVO.BASE,
  PUT = EFECTIVO.BASE + "/",
  DELETE = EFECTIVO.BASE + "/",
}
enum RMCATEGORIA {
  BASE = "umcategoria",
  GETBYCATEGORIA = RMCATEGORIA.BASE + "/getByCategoria/",
  GET = RMCATEGORIA.BASE,
  GETALL = RMCATEGORIA.BASE + "/all",
  FIND = RMCATEGORIA.BASE + "/",
  POST = RMCATEGORIA.BASE,
  PUT = RMCATEGORIA.BASE + "/",
  DELETE = RMCATEGORIA.BASE + "/",
}
enum RMUNIDADMEDIDA {
  BASE = "unidadmedida",
  GETBYCATEGORIA = RMUNIDADMEDIDA.BASE + "/getByCategoria/",
  GET = RMUNIDADMEDIDA.BASE,
  GETALL = RMUNIDADMEDIDA.BASE + "/all",
  FIND = RMUNIDADMEDIDA.BASE + "/",
  POST = RMUNIDADMEDIDA.BASE,
  PUT = RMUNIDADMEDIDA.BASE + "/",
  DELETE = RMUNIDADMEDIDA.BASE + "/",
}

enum REGISTROCAJA {
  BASE = "http://lks.dyndns.info:8002/",
  GETALLBYFECHA = REGISTROCAJA.BASE + "vfecha/",
}

enum TARIFA {
  BASE = "prodTarifa",
  GET = TARIFA.BASE,
  GETALL = TARIFA.BASE + "/all",
  FIND = TARIFA.BASE + "/",
  POST = TARIFA.BASE,
  PUT = TARIFA.BASE + "/",
  DELETE = TARIFA.BASE + "/",
}
enum PVCONFIG {
  BASE = "pvConfig",
  GET = PVCONFIG.BASE,
  GETALL = PVCONFIG.BASE + "/all",
  FIND = PVCONFIG.BASE + "/",
  POST = PVCONFIG.BASE,
  PUT = PVCONFIG.BASE + "/",
  DELETE = PVCONFIG.BASE + "/",
}
enum TIPOMOVIMIENTO {
  BASE = "tipoMovimiento",
  GET = TIPOMOVIMIENTO.BASE,
  GETALL = TIPOMOVIMIENTO.BASE + "/all",
  FIND = TIPOMOVIMIENTO.BASE + "/",
  POST = TIPOMOVIMIENTO.BASE,
  PUT = TIPOMOVIMIENTO.BASE + "/",
  DELETE = TIPOMOVIMIENTO.BASE + "/",
}
enum TIPOTERMINAL {
  BASE = "tipoTerminal",
  GET = TIPOTERMINAL.BASE,
  GETALL = TIPOTERMINAL.BASE + "/all",
  FIND = TIPOTERMINAL.BASE + "/",
  POST = TIPOTERMINAL.BASE,
  PUT = TIPOTERMINAL.BASE + "/",
  DELETE = TIPOTERMINAL.BASE + "/",
}
enum MOVIMIENTO {
  BASE = "movimiento",
  GET = MOVIMIENTO.BASE,
  GETALL = MOVIMIENTO.BASE + "/all",
  FIND = MOVIMIENTO.BASE + "/",
  POST = MOVIMIENTO.BASE,
  PUT = MOVIMIENTO.BASE + "/",
  DELETE = MOVIMIENTO.BASE + "/",
}
enum INGRESOEXTRA {
  BASE = "ingresoExtra",
  GET = INGRESOEXTRA.BASE,
  GETALL = INGRESOEXTRA.BASE + "/all",
  FIND = INGRESOEXTRA.BASE + "/",
  POST = INGRESOEXTRA.BASE,
  PUT = INGRESOEXTRA.BASE + "/",
  DELETE = INGRESOEXTRA.BASE + "/",
}

enum SALDOFAVOR {
  BASE = "saldoFavor",
  GET = SALDOFAVOR.BASE,
  GETALL = SALDOFAVOR.BASE + "/all",
  FIND = SALDOFAVOR.BASE + "/",
  POST = SALDOFAVOR.BASE,
  PUT = SALDOFAVOR.BASE + "/",
  DELETE = SALDOFAVOR.BASE + "/",
}
enum ENTREGAEFECTIVO {
  BASE = "entregaEfectivo",
  GET = ENTREGAEFECTIVO.BASE,
  GETALL = ENTREGAEFECTIVO.BASE + "/all",
  FIND = ENTREGAEFECTIVO.BASE + "/",
  POST = ENTREGAEFECTIVO.BASE,
  PUT = ENTREGAEFECTIVO.BASE + "/",
  DELETE = ENTREGAEFECTIVO.BASE + "/",
}
enum CONFIG {
  BASE = "usuarioConfiguracion",
  GET = CONFIG.BASE,
  POST = CONFIG.BASE,
}

enum STATIC {
  BASE = "Static",
  PRODUCT = STATIC.BASE + "/Producto/",
}

enum CUENTASACTIVOS {
  BASE = "cuentasActivos",
  GET = CUENTASACTIVOS.BASE,
  POST = CUENTASACTIVOS.BASE,
  PUT = CUENTASACTIVOS.BASE + "/",
  DELETE = CUENTASACTIVOS.BASE + "/",
}

enum CAJA {
  BASE = "pvCaja",
  GET = CAJA.BASE,
  GETALL = CAJA.BASE + "/all",
  GETTODAY = CAJA.BASE + "/today",
  DESCRIPTIONS = CAJA.BASE + "/description",
  FIND = CAJA.BASE + "/",
  POST = CAJA.BASE + "/",
  PUT = CAJA.BASE + "/edit",
  DELETE = CAJA.BASE + "/",
}

enum REGISTROGASTOS {
  BASE = "registroGastos",
  GET = REGISTROGASTOS.BASE,
  POST = REGISTROGASTOS.BASE,
  PUT = REGISTROGASTOS.BASE + "/",
  DELETE = REGISTROGASTOS.BASE + "/",
}
enum CIUDAD {
  BASE = "ciudad",
  GET = CIUDAD.BASE,
  POST = CIUDAD.BASE,
  PUT = CIUDAD.BASE + "/",
  DELETE = CIUDAD.BASE + "/",
}
enum PROVINCIA {
  BASE = "provincia",
  GET = PROVINCIA.BASE,
  POST = PROVINCIA.BASE,
  PUT = PROVINCIA.BASE + "/",
  DELETE = PROVINCIA.BASE + "/",
}
enum MUNICIPIO {
  BASE = "municipio",
  GET = MUNICIPIO.BASE,
  POST = MUNICIPIO.BASE,
  PUT = MUNICIPIO.BASE + "/",
  DELETE = MUNICIPIO.BASE + "/",
}
enum CENTRO {
  BASE = "centro",
  GET = CENTRO.BASE,
  POST = CENTRO.BASE,
  PUT = CENTRO.BASE + "/",
  DELETE = CENTRO.BASE + "/",
}
enum LABORATORIO {
  BASE = "laboratorio",
  GET = LABORATORIO.BASE,
  POST = LABORATORIO.BASE,
  PUT = LABORATORIO.BASE + "/",
  DELETE = LABORATORIO.BASE + "/",
}
enum MANEJOCARTILLA {
  BASE = "manejoCartilla",
  GET = MANEJOCARTILLA.BASE,
  POST = MANEJOCARTILLA.BASE,
  PUT = MANEJOCARTILLA.BASE + "/",
  DELETE = MANEJOCARTILLA.BASE + "/",
  GETPROVINCIA = MANEJOCARTILLA.BASE + "/provincia",
  GETHOSPITAL = MANEJOCARTILLA.BASE + "/hospital",
  GETFALTANTE = MANEJOCARTILLA.BASE + "/faltantes",
}
enum CARTILLA {
  BASE = "cartilla",
  GET = CARTILLA.BASE,
  POST = CARTILLA.BASE,
  PUT = CARTILLA.BASE + "/",
  DELETE = CARTILLA.BASE + "/",
  RESULTADONULL = CARTILLA.BASE + "/cartillaSinResultado",
}
enum RESULTADO {
  BASE = "resultado",
  GET = RESULTADO.BASE,
  POST = RESULTADO.BASE,
  PUT = RESULTADO.BASE + "/",
  DELETE = RESULTADO.BASE + "/",
  GETALL = RESULTADO.BASE + "/all",
  GETPENDIENTE = RESULTADO.BASE + "/resultadoPendiente",
  GETPENDIENTEENVIO = RESULTADO.BASE + "/resultadoPendienteEnvio",
  POSITIVO = RESULTADO.BASE + "/pacientePositivo",
  NEGATIVO = RESULTADO.BASE + "/pacienteNegativo",
  DAY = RESULTADO.BASE + "/day",
  PENDIENTEENVIO = RESULTADO.BASE + "/envioPendientes",
}

enum PACIENTE {
  BASE = "paciente",
  GET = PACIENTE.BASE,
  POST = PACIENTE.BASE,
  PUT = PACIENTE.BASE + "/",
  DELETE = PACIENTE.BASE + "/",
  GETALL = PACIENTE.BASE + "/all",
  GETPOSITIVO = PACIENTE.BASE + "/pacientesPositivos",
  GETNEGATIVO = PACIENTE.BASE + "/pacientesNegativos",
}
enum COMMON {
  BASE = "common",
  DATA = COMMON.BASE + "/data",
}

export const ENDPOINTS = {
  CIUDAD,
  PACIENTE,
  CARTILLA,
  RESULTADO,
  LABORATORIO,
  MANEJOCARTILLA,
  CENTRO,
  MUNICIPIO,
  PROVINCIA,
  CUENTAS,
  ASIENTOS,
  TIPOCOMPROBANTES,
  DETALLEASIENTOS,
  CATEGORIAS,
  MODULOCATEGORIA,
  CONTACTO,
  CATEGORIACONTACTO,
  GRUPO,
  MENU,
  PRODUCTO,
  USUARIO,
  MODELO,
  PRODUCTOBASE,
  PRODUCTOCATEGORIA,
  BANCOS,
  CONFIG,
  TIPOCAMBIO,
  ATRIBUTO,
  ATRIBUTOVALOR,
  STATIC,
  COMPRAORDEN,
  EMPRESA,
  LIBRODIARIO,
  COMPARTIRLIBRODIARIO,
  VENTAORDEN,
  BANCO,
  CONTACTOBANCO,
  METODOPAGO,
  MONEDA,
  EFECTIVO,
  RMCATEGORIA,
  RMUNIDADMEDIDA,
  REGISTROCAJA,
  TARIFA,
  TIPOMOVIMIENTO,
  PVCONFIG,
  TIPOTERMINAL,
  MOVIMIENTO,
  INGRESOEXTRA,
  SALDOFAVOR,
  ENTREGAEFECTIVO,
  CUENTASACTIVOS,
  CAJA,
  REGISTROGASTOS,
  COMMON,
};
