export enum ROUTES {
  
  INDEX = "/",
  REGISTER = "/registro",
  LOGIN="/login",
  INFORMATIVA="/informativa",
  HOME="/home",
  PROGRAMAS="/programas",
  INFORMACION="/informacion",
  CENTROS="/centros",
  CONTACTOS="/contactos",
  
  DASHBOARD = "/dashboard",
  INICIO = ROUTES.DASHBOARD + "/inicio",
  PROFILE = ROUTES.DASHBOARD + "/profile",

  CONTACTO = ROUTES.DASHBOARD + "/contactos",
  CONTACTO_CATEGORIAS = ROUTES.DASHBOARD + "/contactos-categorias",
  CONTACTO_EMPRESA = ROUTES.DASHBOARD + "/contactos-empresa",
  CONTACTO_DETALLE = ROUTES.DASHBOARD + "/contactos/",

  MUNICIPIO = ROUTES.DASHBOARD + "/municipios",
  CENTRO = ROUTES.DASHBOARD + "/centros",
  CARTILLA = ROUTES.DASHBOARD + "/cartilla",
  PACIENTESNEGATIVOS = ROUTES.DASHBOARD + "/paciente-negativo",
  PACIENTESPOSITIVOS = ROUTES.DASHBOARD + "/paciente-positivo",
  PACIENTESTODOS = ROUTES.DASHBOARD + "/paciente-todos",
  FALTANTES = ROUTES.DASHBOARD + "/faltantes",
  TODORESULTADO = ROUTES.DASHBOARD + "/todo-resultados",
  PENDIENTESRESULTADOS = ROUTES.DASHBOARD + "/pendientes-resultados",
  PENDIENTESENVIO = ROUTES.DASHBOARD + "/pendientes-envio",
  NUEVORESULTADO = ROUTES.DASHBOARD + "/nuevo-resultado",
  MANEJOCARTILLA = ROUTES.DASHBOARD + "/provincia-cartilla",
  MANEJOCARTILLAHOSPITAL = ROUTES.DASHBOARD + "/hospital-cartilla",
  LABORATORIO = ROUTES.DASHBOARD + "/laboratorio",
  PROVINCIA = ROUTES.DASHBOARD + "/provincias",
  CIUDAD = ROUTES.DASHBOARD + "/ciudades",
  PUNTO_DE_VENTA_CONFIGURACION_CONFIG = ROUTES.DASHBOARD + "/config",
  CONFIGURACION_USUARIOS = ROUTES.DASHBOARD + "/configuracion-usuarios",
  CONFIGURACION_GRUPOS = ROUTES.DASHBOARD + "/configuracion-grupos",
  CONFIGURACION_MENUS = ROUTES.DASHBOARD + "/configuracion-menus",
  CONFIGURACION_MODELOS = ROUTES.DASHBOARD + "/configuracion-modelos",
  //CONFIGURACION_DECIMALES = ROUTES.DASHBOARD + "/configuracion-decimales",
}
